# Generated by Django 2.0.7 on 2019-04-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharmacy_Name', models.CharField(max_length=60)),
                ('URL', models.CharField(max_length=60)),
                ('Street_Address', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('Zip', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=60)),
                ('Conditions', models.CharField(max_length=60)),
                ('Company', models.CharField(max_length=60)),
                ('Type', models.CharField(max_length=60)),
                ('Pharmacy', models.CharField(max_length=60)),
                ('Contact', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Accreditation', models.CharField(max_length=60)),
                ('Owner_Independent', models.CharField(max_length=60)),
                ('Patient_Services', models.CharField(max_length=60)),
                ('Payer_Services', models.CharField(max_length=60)),
                ('Pharma_Services', models.CharField(max_length=60)),
                ('Locations', models.CharField(max_length=60)),
                ('Limted_Distribution_Drugs', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='subscription_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Access', models.CharField(max_length=60)),
                ('Duration', models.CharField(max_length=60)),
                ('User_Type', models.CharField(max_length=60)),
                ('Records', models.CharField(max_length=60)),
                ('Cost', models.CharField(max_length=60)),
                ('Renewable', models.CharField(max_length=60)),
                ('Trial', models.CharField(max_length=60)),
            ],
        ),
    ]
