# Generated by Django 2.0.7 on 2019-04-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_subscription_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Access', models.CharField(max_length=60)),
                ('Duration', models.CharField(max_length=60)),
                ('User_Type', models.CharField(max_length=60)),
                ('Records', models.CharField(max_length=60)),
                ('Cost', models.CharField(max_length=60)),
                ('Renewable', models.CharField(max_length=60)),
                ('Trial', models.CharField(max_length=60)),
            ],
        ),
    ]
