# Generated by Django 2.0.7 on 2019-04-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0004_auto_20190408_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_options_duration',
            name='calendar_days',
            field=models.IntegerField(choices=[('7 Days', 7), ('1 Month', 31), ('12 Months', 365)], help_text='Choose A Day Value', null=True),
        ),
    ]
