# Generated by Django 2.0.7 on 2019-04-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0006_auto_20190408_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_options_duration',
            old_name='name',
            new_name='display_name',
        ),
    ]
