# Generated by Django 2.0.7 on 2019-04-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0009_test_fk_subscription_type_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_options_access',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='subscription_options_cost',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='subscription_options_records',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='subscription_options_renewable',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='subscription_options_trial',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='subscription_options_user_type',
            old_name='name',
            new_name='display_name',
        ),
    ]
