# Generated by Django 2.0.7 on 2019-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0013_auto_20190408_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_options_records',
            name='display',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
