# Generated by Django 2.0.7 on 2019-04-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0014_auto_20190408_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_options_renewable',
            name='_is',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_fk_subscription_type',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
