# Generated by Django 2.0.7 on 2019-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0015_auto_20190408_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_options_renewable',
            old_name='_is',
            new_name='is_renewable',
        ),
        migrations.AddField(
            model_name='subscription_options_trial',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
