# Generated by Django 2.0.7 on 2019-04-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0016_auto_20190408_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_options_cost',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
