# Generated by Django 2.0.7 on 2019-04-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0019_test_fk_subscription_type_testing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacies',
            old_name='Company',
            new_name='Contact_Email',
        ),
        migrations.RemoveField(
            model_name='pharmacies',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='pharmacies',
            name='Pharmacy',
        ),
        migrations.RemoveField(
            model_name='pharmacies',
            name='Pharmacy_Name',
        ),
        migrations.RemoveField(
            model_name='pharmacies',
            name='Street_Address',
        ),
        migrations.RemoveField(
            model_name='pharmacies',
            name='Type',
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='Company_Type',
            field=models.CharField(default='derp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='Name',
            field=models.CharField(default='derp_name', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='Street',
            field=models.CharField(default='derp_street', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='City',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Conditions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Locations',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='State',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='URL',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Zip',
            field=models.IntegerField(),
        ),
    ]
