# Generated by Django 2.0.7 on 2019-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0021_pharmacies_state_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
