# Generated by Django 2.0.7 on 2019-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0022_auto_20190408_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='Accreditation',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='City',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Company_Type',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Contact',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Contact_Email',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Limted_Distribution_Drugs',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Locations',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Name',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Owner_Independent',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Patient_Services',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Payer_Services',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Pharma_Services',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='State',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='State_full',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Street',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='URL',
            field=models.URLField(max_length=4000),
        ),
    ]
