# Generated by Django 2.0.7 on 2019-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0023_auto_20190408_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='Accreditation',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Contact',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Contact_Email',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Limted_Distribution_Drugs',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Owner_Independent',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Patient_Services',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Payer_Services',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='Pharma_Services',
            field=models.CharField(max_length=6000),
        ),
    ]
