# Generated by Django 2.0.7 on 2019-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0024_auto_20190408_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacies',
            name='Zip',
            field=models.CharField(max_length=50),
        ),
    ]
