# Generated by Django 2.0.7 on 2019-11-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options_Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options_Cost',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options_Duration',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('calendar_days', models.IntegerField(help_text='How Many Calendar Days Does The Subscription Run For?', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options_Records',
            fields=[
                ('display', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('records', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options_Renewable',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('is_renewable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Options_Trial',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('is_trial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Options_User_Type',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('max_users', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='subscriptions_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_name', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField(null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Testing', models.BooleanField(default=False)),
                ('Access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Access')),
                ('Cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Cost')),
                ('Duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Duration')),
                ('Records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Records')),
                ('Renewable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Renewable')),
                ('Trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Trial')),
                ('User_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_User_Type')),
            ],
        ),
    ]
