# Generated by Django 2.0.7 on 2020-01-07 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options_Descript_Dur',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Options_Descript_Type',
            fields=[
                ('display', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptions_type',
            name='descript_dur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Descript_Dur'),
        ),
        migrations.AddField(
            model_name='subscriptions_type',
            name='descript_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscripts.Options_Descript_Type'),
        ),
    ]
