# Generated by Django 2.0.7 on 2019-08-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('org_name', models.CharField(max_length=60, null=True)),
                ('org_type', models.CharField(max_length=60, null=True)),
                ('org_age', models.CharField(max_length=60, null=True)),
                ('org_location', models.CharField(max_length=60, null=True)),
                ('org_leadership_ethnicity', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
